site_name: Escrow system common errors

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

copyright: Copyright &copy; 2021 - 2022 jaksam1074#6183

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7prxECaP6J

nav:
    - 'index.md'
    - 'error_parsing_script.md'
    - 'failed_to_verify_protected_resource.md'
    - 'wrong_license.md'
    - 'nothing_works.md'